### ISSUE TITLE
Status value is still 0 even after successful websocket connection

### ISSUE THREAD

**Issue by Boscop** [wburgers/websocket-component#6]
Thanks for this great element, it works but I have one small problem with it:
The component's `status` value is still 0 even after a successful websocket connection.
But it should be 1 after successful connection:
https://developer.mozilla.org/en/docs/Web/API/WebSocket#Ready_state_constants

https://stackoverflow.com/a/21120798/7488353
> In order to trigger some functionality when WebSockets are connected please use callbacks.

> Using readyState is well bad thing to do in such case

So I guess `_onwsopen` should set the status to 1?

**Comment by wburgers** [comment]
Hi,

Sorry for the late response.
The status value is a computed value derived from the readyState of the websocket.
It is not set manually in the component, but it is observed.
If the readyState of the websocket changes, it is reflected in the status value of this component.

So if the status value is still 0 after a successful connection, the websocket.readyState is not updated by the browser.
It is possible to perform a manual check on the readyState in _onwsopen, but that should not be necessary.
I don't think it is wise to set the status value in _onwsopen.
